# Base Configuration for Auth Service
# Environment-specific configurations are in application-{profile}.yml files

spring:
  application:
    name: auth-service

# Server Configuration
server:
  port: 8082
  servlet:
    context-path: /

# JWT Configuration - Common settings
jwt:
  secret: ${JWT_SECRET:dev_secret_key_XK7fJ3mP9vN2wQ8rT5yU6iO1pA4sD7fG9hJ2kL5nM8qR3tY6uI9oP2aS5dF8gH1jK4lZ7xC0vB3nM6qW9eR2tY5uI8oP1aS4dF7gH0jK3lZ6xC9vB2nM5qW8eR1tY4u==}
  access-token-expiration: 7200000 # 2 hours
  refresh-token-expiration: 604800000 # 7 days

# Security Configuration - Common settings
app:
  security:
    password-reset-token-expiration-minutes: 60
    max-failed-attempts: 5
    lockout-duration-minutes: 30

  # Admin User Configuration
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:?ADMIN_PASSWORD required}
    email: ${ADMIN_EMAIL:admin@example.com}
    enabled: ${ADMIN_ENABLED:true}

  # Enhanced Synchronization Configuration
  kafka:
    topic:
      user-events: ${KAFKA_USER_EVENTS_TOPIC:user-events}

  sync:
    max-retry-attempts: 5
    retry-delay-seconds: 30

  circuit-breaker:
    failure-threshold: 5
    timeout-seconds: 60
    half-open-max-calls: 3

  health:
    user-service-timeout: 5000

# Kafka Topics - Common configuration
kafka:
  topics:
    user-events: user-events
    user-events-dlq: user-events-dlq

# Outbox Pattern - Common configuration
outbox:
  scheduler:
    enabled: true
    fixed-delay: 5000 # 5 seconds
    batch-size: 100

# Service URLs
user:
  service:
    url: ${USER_SERVICE_URL:http://user-service:8081}

# Internal API Key for service-to-service communication (standardized)
internal:
  api:
    key: ${INTERNAL_API_KEY:?INTERNAL_API_KEY required}
