# Base Configuration for Auth Service
# Environment-specific configurations are in application-{profile}.yml files

spring:
  application:
    name: auth-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Server Configuration
server:
  port: 8082
  servlet:
    context-path: /

# JWT Configuration - Common settings
jwt:
  access-token-expiration: 900000 # 15 minutes
  refresh-token-expiration: 604800000 # 7 days

# Security Configuration - Common settings
app:
  security:
    password-reset-token-expiration-minutes: 60

# Kafka Topics - Common configuration
kafka:
  topics:
    user-events: user-events
    user-events-dlq: user-events-dlq

# Outbox Pattern - Common configuration
outbox:
  scheduler:
    enabled: true
    fixed-delay: 5000 # 5 seconds
    batch-size: 100
