# Production Environment Configuration for Notification Service
spring:
  profiles:
    active: prod

  # Database Configuration - PostgreSQL for production
  datasource:
    url: ${DB_URL:jdbc:postgresql://notification-db:5432/notificationdb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:notificationuser}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      validation-timeout: 5000
      connection-test-query: SELECT 1

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        order_updates: true
        batch_size: 25
        batch_versioned_data: true

  # H2 Console disabled in production
  h2:
    console:
      enabled: false

  # Redis Configuration - Production Redis Cluster
  data:
    redis:
      host: ${REDIS_HOST:redis-cluster}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 5000ms
        cluster:
          refresh:
            adaptive: true
            period: 30s

  # Kafka Configuration - Production Kafka Cluster
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-cluster:9092}
    consumer:
      group-id: notification-service-prod
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      max-poll-records: 500
      session-timeout-ms: 30000
      heartbeat-interval-ms: 10000
      properties:
        isolation.level: read_committed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 5
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
        compression.type: snappy

  # Mail Configuration - Production SMTP
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
    default-encoding: UTF-8

  # Security Configuration - Strict for production
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:-admin123} # REQUIRED - Must be set in production
      roles: ADMIN

  # Async Task Configuration - Optimized for production
  task:
    execution:
      pool:
        core-size: 10
        max-size: 50
        queue-capacity: 200
        keep-alive: 60s
        thread-name-prefix: notification-async-

# Resilience4j Configuration - Strict for production
resilience4j:
  circuitbreaker:
    instances:
      emailService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      redisService:
        failure-rate-threshold: 30
        wait-duration-in-open-state: 15s
        sliding-window-size: 20
        minimum-number-of-calls: 10
        permitted-number-of-calls-in-half-open-state: 5
  retry:
    instances:
      emailService:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - java.lang.Exception
      redisService:
        max-attempts: 2
        wait-duration: 500ms
        retry-exceptions:
          - java.lang.Exception
  bulkhead:
    instances:
      emailService:
        max-concurrent-calls: 10
        max-wait-duration: 5s
      redisService:
        max-concurrent-calls: 15
        max-wait-duration: 5s
  ratelimiter:
    instances:
      emailService:
        limit-for-period: 20
        limit-refresh-period: 1m
        timeout-duration: 5s
      redisService:
        limit-for-period: 30
        limit-refresh-period: 1m
        timeout-duration: 5s

# Management Configuration - Restricted for production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,retries,bulkheads,ratelimiters
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 500ms

# OpenAPI Configuration - Restricted for production
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    try-it-out-enabled: false # Disabled in production

# Logging Configuration - Optimized for production
logging:
  level:
    root: WARN
    com.microservices.notificationservice: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: ERROR
    io.github.resilience4j: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %X{correlationId} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %X{correlationId} - %msg%n"
  file:
    name: logs/notification-service-prod.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 10GB

# Kafka Topics Configuration
kafka:
  topics:
    user-events: user-events-prod
    order-events: order-events-prod
    order-notifications: order-events-prod
    user-events-dlq: user-events-dlq-prod
    order-events-dlq: order-events-dlq-prod
    order-notifications-dlq: order-events-dlq-prod

# Idempotency Configuration - Optimized for production
idempotency:
  redis:
    key-prefix: "notification:prod:"
    ttl-seconds: 7200 # 2 hours

# Server Configuration
server:
  port: 8085
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    connection-timeout: 20000
    max-connections: 8192
    accept-count: 100
