spring:
  application:
    name: notification-service
  profiles:
    active: dev

server:
  port: 8085

logging:
  level:
    com.microservices.notificationservice: DEBUG
    org.springframework.kafka: INFO
    org.springframework.security: DEBUG
