# Development Environment Configuration for Notification Service

spring:
  # Database Configuration - H2 for development
  datasource:
    url: jdbc:h2:mem:notificationdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: UTC

  # H2 Console for development
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # Redis Configuration - Docker Redis
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # Kafka Configuration - Docker Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      group-id: notification-service-dev
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      properties:
        isolation.level: read_committed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1

  # Mail Configuration - Gmail SMTP for testing
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:souravsingh2609@gmail.com}
    password: ${MAIL_PASSWORD:bhooqxmxjnwkccgb}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
    test-connection: false # Disable mail connection test in dev

  # Security Configuration - Relaxed for development
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# Custom Security Configuration
security:
  admin:
    username: admin
    password: admin123

  # Async Task Configuration - Relaxed for development
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100
        keep-alive: 60s
        thread-name-prefix: notification-async-

# Resilience4j Configuration - Relaxed for development
resilience4j:
  circuitbreaker:
    instances:
      emailService:
        failure-rate-threshold: 70 # More lenient
        wait-duration-in-open-state: 10s
        sliding-window-size: 5
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 2
      redisService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        sliding-window-size: 5
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 2
  retry:
    instances:
      emailService:
        max-attempts: 2 # Fewer retries
        wait-duration: 1s
      redisService:
        max-attempts: 2
        wait-duration: 200ms
  bulkhead:
    instances:
      emailService:
        max-concurrent-calls: 20 # More lenient
        max-wait-duration: 2s
      redisService:
        max-concurrent-calls: 15
        max-wait-duration: 2s
  ratelimiter:
    instances:
      emailService:
        limit-for-period: 30 # More lenient
        limit-refresh-period: 1m
        timeout-duration: 2s
      redisService:
        limit-for-period: 50
        limit-refresh-period: 1m
        timeout-duration: 2s

# Management Configuration - Full exposure for development
management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all endpoints
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99

# OpenAPI Configuration - Full access for development
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true

# Logging Configuration - Verbose for development
logging:
  level:
    root: INFO
    com.microservices.notificationservice: DEBUG
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO
    io.github.resilience4j: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %X{correlationId} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %X{correlationId} - %msg%n"
  file:
    name: logs/notification-service-dev.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7 # Keep fewer logs in development

# Kafka Topics Configuration
kafka:
  topics:
    user-events: user-events-dev
    order-events: order-events-dev
    order-notifications: order-events-dev
    user-events-dlq: user-events-dlq-dev
    order-notifications-dlq: order-events-dlq-dev

# Idempotency Configuration - Relaxed for development
idempotency:
  redis:
    key-prefix: "notification:dev:"
    ttl-seconds: 3600 # 1 hour
