server:
  port: 8080
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: api-gateway

  lifecycle:
    timeout-per-shutdown-phase: 30s

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:devredis123}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 5000
            response-timeout: 10s
            pool:
              type: elastic
              max-connections: 500
              max-idle-time: 30s

          globalcors:
            cors-configurations:
              "[/**]":
                # Frontend URLs
                allowedOrigins:
                  - "http://localhost:5173"
                  - "http://127.0.0.1:5173"
                  - "http://localhost:3000"
                  - "http://127.0.0.1:3000"
                allowedOriginPatterns:
                  - "http://localhost:*"
                  - "http://127.0.0.1:*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowedHeaders: "*"
                exposedHeaders:
                  - Authorization
                  - Content-Type
                allowCredentials: true
                maxAge: 3600

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
        # Note: RequestRateLimiter removed from default-filters to allow Swagger endpoints
        # Rate limiting is applied individually to routes that need it

# JWT Configuration
jwt:
  # IMPORTANT: Use environment variable in production
  # Generate with: openssl rand -base64 64
  secret: ${JWT_SECRET:dev_secret_key_XK7fJ3mP9vN2wQ8rT5yU6iO1pA4sD7fG9hJ2kL5nM8qR3tY6uI9oP2aS5dF8gH1jK4lZ7xC0vB3nM6qW9eR2tY5uI8oP1aS4dF7gH0jK3lZ6xC9vB2nM5qW8eR1tY4u==}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour in milliseconds

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

# Rate Limiting Configuration
rate-limit:
  enabled: true
  capacity: 100
  refill-tokens: 100
  refill-duration-minutes: 1

# Service URLs
auth-service:
  url: ${AUTH_SERVICE_URL:http://auth-service:8082}

user-service:
  url: ${USER_SERVICE_URL:http://user-service:8081}

order-service:
  url: ${ORDER_SERVICE_URL:http://order-service:8083}

inventory-service:
  url: ${INVENTORY_SERVICE_URL:http://inventory-service:8084}

notification-service:
  url: ${NOTIFICATION_SERVICE_URL:http://host.docker.internal:8085}

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  prometheus:
    metrics:
      export:
        enabled: true

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      authServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      userServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      userServiceGraphQLCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      orderServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      inventoryServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

  timelimiter:
    instances:
      authServiceCircuitBreaker:
        timeoutDuration: 10s
      userServiceCircuitBreaker:
        timeoutDuration: 10s
      userServiceGraphQLCircuitBreaker:
        timeoutDuration: 15s
      orderServiceCircuitBreaker:
        timeoutDuration: 10s
      inventoryServiceCircuitBreaker:
        timeoutDuration: 10s

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.microservices.apigateway: DEBUG
    io.github.resilience4j: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/api-gateway.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
