global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8082"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s

  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:8081"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:8085"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8080"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
