# Docker Environment Configuration for User Service
spring:
  # Database Configuration - PostgreSQL for Docker
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres-user:5432/userdb}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:useruser}
    password: ${DATABASE_PASSWORD:userpassword123}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  # Flyway Configuration - Disabled for development
  flyway:
    # enabled: true
    # locations: classpath:db/migration
    # baseline-on-migrate: true
    # validate-on-migrate: true
    enabled: false

  # GraphQL Configuration - Full access for development
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      locations: classpath:graphql/
      file-extensions: .graphqls
      introspection:
        enabled: true
    cors:
      allowed-origins: http://localhost:3000,http://localhost:5173,http://localhost:8080,http://localhost:8081,http://localhost:8082
      allowed-methods: "*"
    http:
      path: /graphql

  # Redis Configuration - Docker Redis
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # Kafka Configuration - Docker Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432

# Server Configuration
server:
  port: 8081

# Auth Service Configuration - Development
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://auth-service:8082}
    validate-endpoint: /api/auth/validate

# JWT Configuration - Development Secret
jwt:
  secret: ${JWT_SECRET:dev_secret_key_XK7fJ3mP9vN2wQ8rT5yU6iO1pA4sD7fG9hJ2kL5nM8qR3tY6uI9oP2aS5dF8gH1jK4lZ7xC0vB3nM6qW9eR2tY5uI8oP1aS4dF7gH0jK3lZ6xC9vB2nM5qW8eR1tY4u==}

internal:
  api:
    key: ${INTERNAL_API_KEY:internal-api-key-123}
app:
  security:
    max-requests-per-minute: 200
    max-graphql-depth: 15
    max-graphql-complexity: 2000

  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173,http://localhost:8080,http://localhost:8081,http://localhost:8082
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-headers: "*"
    allow-credentials: true

# Resilience4j Configuration - Relaxed for development
resilience4j:
  circuitbreaker:
    instances:
      authService:
        failure-rate-threshold: 70 # More lenient
        wait-duration-in-open-state: 10s
        sliding-window-size: 5
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 2
      kafkaService:
        failure-rate-threshold: 60
        wait-duration-in-open-state: 10s
        sliding-window-size: 5
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 2
      redisService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        sliding-window-size: 5
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 2
  retry:
    instances:
      authService:
        max-attempts: 2 # Fewer retries
        wait-duration: 1s
      kafkaService:
        max-attempts: 2
        wait-duration: 500ms
      redisService:
        max-attempts: 2
        wait-duration: 200ms
  bulkhead:
    instances:
      userOperations:
        max-concurrent-calls: 50 # More lenient
        max-wait-duration: 2s
      graphqlOperations:
        max-concurrent-calls: 30
        max-wait-duration: 2s
  ratelimiter:
    instances:
      userCreation:
        limit-for-period: 50 # More lenient
        limit-refresh-period: 1m
        timeout-duration: 2s
      userUpdate:
        limit-for-period: 100
        limit-refresh-period: 1m
        timeout-duration: 2s
      graphqlQuery:
        limit-for-period: 200
        limit-refresh-period: 1m
        timeout-duration: 2s

# Management Configuration - Full exposure for development
management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all endpoints
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99

# SpringDoc OpenAPI Configuration - Full access for development
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Logging Configuration - Verbose for development
logging:
  level:
    root: INFO
    com.microservices.userservice: DEBUG
    com.microservices.userservice.security: DEBUG
    org.springframework.security: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.graphql: DEBUG
    org.apache.kafka: INFO
    io.github.resilience4j: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %X{correlationId} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %X{correlationId} - %msg%n"
  file:
    name: logs/user-service-dev.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7 # Keep fewer logs in development
