# Base Configuration for User Service
# Environment-specific configurations are in application-{profile}.yml files

spring:
  application:
    name: user-service

  main:
    allow-bean-definition-overriding: true

  # GraphQL Configuration - Common settings
  graphql:
    schema:
      locations: classpath:graphql/
      file-extensions: .graphqls
    http:
      path: /graphql

# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /

# Auth Service Configuration - Common settings
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://auth-service:8082}
    validate-endpoint: /api/auth/validate

# Admin User Configuration (for profile sync)
app:
  admin:
    username: ${ADMIN_USERNAME:admin}
    email: ${ADMIN_EMAIL:admin@example.com}
    firstName: ${ADMIN_FIRST_NAME:Admin}
    lastName: ${ADMIN_LAST_NAME:User}
    enabled: ${ADMIN_ENABLED:true}

  # Enhanced Synchronization Configuration
  reconciliation:
    enabled: true
    batch-size: 100
    max-age-hours: 24

# Internal API Key for service-to-service communication (standardized)
internal:
  api:
    key: ${INTERNAL_API_KEY:internal-api-key-123}

# SpringDoc OpenAPI Configuration - Common settings
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
    filter: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
