# Base Configuration for User Service
# Environment-specific configurations are in application-{profile}.yml files

spring:
  application:
    name: user-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # GraphQL Configuration - Common settings
  graphql:
    schema:
      locations: classpath:graphql/
      file-extensions: .graphqls
    http:
      path: /graphql

# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /

# Auth Service Configuration - Common settings
auth:
  service:
    validate-endpoint: /api/auth/validate
