# Staging Environment Configuration for User Service
spring:
  profiles:
    active: staging

  # Database Configuration - PostgreSQL for staging
  datasource:
    url: ${DB_URL:jdbc:postgresql://user-db-staging:5432/userdb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:useruser}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 15
      minimum-idle: 3
      connection-timeout: 25000
      idle-timeout: 450000
      max-lifetime: 1500000
      leak-detection-threshold: 60000
      validation-timeout: 5000
      connection-test-query: SELECT 1

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update # Allow schema updates in staging
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        order_updates: true
        batch_size: 20
        batch_versioned_data: true

  # SQL Initialization disabled in staging
  sql:
    init:
      mode: never

  # H2 Console disabled in staging
  h2:
    console:
      enabled: false

  # GraphQL Configuration - Moderate access for staging
  graphql:
    graphiql:
      enabled: true # Enabled for testing
    schema:
      locations: classpath:graphql/
      file-extensions: .graphqls
      introspection:
        enabled: true # Enabled for testing
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:https://staging.yourdomain.com,http://localhost:3000,http://localhost:5173}
      allowed-methods: POST,OPTIONS,GET
    http:
      path: /graphql

  # Redis Configuration - Staging Redis
  data:
    redis:
      host: ${REDIS_HOST:redis-staging}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 15
          max-idle: 8
          min-idle: 3
          max-wait: 3000ms

  # Kafka Configuration - Staging Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-staging:9092}
    consumer:
      group-id: user-service-staging
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      max-poll-records: 500
      session-timeout-ms: 30000
      heartbeat-interval-ms: 10000
      properties:
        isolation.level: read_committed

# Auth Service Configuration - Staging
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://auth-service-staging:8082}
    validate-endpoint: /api/auth/validate

# JWT Configuration - Staging Secret
jwt:
  secret: ${JWT_SECRET:staging_secret_key_XK7fJ3mP9vN2wQ8rT5yU6iO1pA4sD7fG9hJ2kL5nM8qR3tY6uI9oP2aS5dF8gH1jK4lZ7xC0vB3nM6qW9eR2tY5uI8oP1aS4dF7gH0jK3lZ6xC9vB2nM5qW8eR1tY4u==}

# Security Configuration - Balanced for staging
app:
  security:
    internal-api-key: ${INTERNAL_API_KEY:staging-internal-api-key}
    max-requests-per-minute: 150 # Moderate limits
    max-graphql-depth: 12 # Moderate depth
    max-graphql-complexity: 1500 # Moderate complexity

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://staging.yourdomain.com,http://localhost:3000,http://localhost:5173}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-headers: Authorization,Content-Type,X-Requested-With
    allow-credentials: true

# Resilience4j Configuration - Balanced for staging
resilience4j:
  circuitbreaker:
    instances:
      authService:
        failure-rate-threshold: 60 # Moderate threshold
        wait-duration-in-open-state: 20s
        sliding-window-size: 8
        minimum-number-of-calls: 4
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      kafkaService:
        failure-rate-threshold: 45
        wait-duration-in-open-state: 15s
        sliding-window-size: 12
        minimum-number-of-calls: 6
        permitted-number-of-calls-in-half-open-state: 4
      redisService:
        failure-rate-threshold: 35
        wait-duration-in-open-state: 10s
        sliding-window-size: 15
        minimum-number-of-calls: 8
        permitted-number-of-calls-in-half-open-state: 4
  retry:
    instances:
      authService:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.lang.Exception
      kafkaService:
        max-attempts: 2
        wait-duration: 750ms
        retry-exceptions:
          - java.lang.Exception
      redisService:
        max-attempts: 2
        wait-duration: 300ms
        retry-exceptions:
          - java.lang.Exception
  bulkhead:
    instances:
      userOperations:
        max-concurrent-calls: 40 # Moderate concurrency
        max-wait-duration: 3s
      graphqlOperations:
        max-concurrent-calls: 25
        max-wait-duration: 3s
  ratelimiter:
    instances:
      userCreation:
        limit-for-period: 30 # Moderate limits
        limit-refresh-period: 1m
        timeout-duration: 3s
      userUpdate:
        limit-for-period: 75
        limit-refresh-period: 1m
        timeout-duration: 3s
      graphqlQuery:
        limit-for-period: 150
        limit-refresh-period: 1m
        timeout-duration: 3s

# Management Configuration - Moderate exposure for staging
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,retries,bulkheads,ratelimiters,beans,env
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 500ms

# OpenAPI Configuration - Moderate access for staging
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    try-it-out-enabled: true # Enabled for testing

# Logging Configuration - Moderate verbosity for staging
logging:
  level:
    root: INFO
    com.microservices.userservice: DEBUG
    org.springframework.security: INFO
    org.springframework.kafka: INFO
    org.springframework.graphql: INFO
    org.apache.kafka: WARN
    io.github.resilience4j: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %X{correlationId} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %X{correlationId} - %msg%n"
  file:
    name: logs/user-service-staging.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 14 # Keep logs for 2 weeks
      total-size-cap: 5GB

# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  tomcat:
    max-threads: 150
    min-spare-threads: 8
    connection-timeout: 20000
    max-connections: 6144
    accept-count: 100
