# Base Configuration for Order Service
# Environment-specific configurations are in application-{profile}.yml files

spring:
  application:
    name: order-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Server Configuration
server:
  port: 8083
  servlet:
    context-path: /

# Auth Service Configuration - Common settings
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://auth-service:8082}
    validate-endpoint: /api/auth/validate

# User Service Configuration - Common settings
user:
  service:
    url: ${USER_SERVICE_URL:http://user-service:8081}

# Inventory Service Configuration - Common settings
inventory:
  service:
    url: ${INVENTORY_SERVICE_URL:http://inventory-service:8084}

# JWT Configuration - Common settings
jwt:
  secret: ${JWT_SECRET:dev_secret_key_XK7fJ3mP9vN2wQ8rT5yU6iO1pA4sD7fG9hJ2kL5nM8qR3tY6uI9oP2aS5dF8gH1jK4lZ7xC0vB3nM6qW9eR2tY5uI8oP1aS4dF7gH0jK3lZ6xC9vB2nM5qW8eR1tY4u==}

# Security Configuration - Common settings
app:
  security:
    internal-api-key: ${INTERNAL_API_KEY:prod_7yXJ2mQ9rT5vL8cN1pB4sD7fG0hK3lZ6xC9vB2nM5qW8eR1tY4u}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:8080,http://localhost:8081,http://localhost:8082,http://localhost:8083}

# Kafka Topics - Common configuration
kafka:
  topics:
    order-events: order-events
    order-events-dlq: order-events-dlq

# SpringDoc OpenAPI Configuration - Common settings
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

