# Base Configuration for Inventory Service
# Environment-specific configurations are in application-{profile}.yml files

spring:
  application:
    name: inventory-service

# Server Configuration
server:
  port: 8084
  servlet:
    context-path: /

# Security Configuration - Common settings
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:8080,http://localhost:8081,http://localhost:8082,http://localhost:8083,http://localhost:8084}

# JWT Configuration - Common settings
jwt:
  secret: ${JWT_SECRET:dev_secret_key_XK7fJ3mP9vN2wQ8rT5yU6iO1pA4sD7fG9hJ2kL5nM8qR3tY6uI9oP2aS5dF8gH1jK4lZ7xC0vB3nM6qW9eR2tY5uI8oP1aS4dF7gH0jK3lZ6xC9vB2nM5qW8eR1tY4u==}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour in milliseconds

# Internal API Key for service-to-service communication (standardized)
internal:
  api:
    key: ${INTERNAL_API_KEY:?INTERNAL_API_KEY required}

# Kafka Topics - Common configuration
kafka:
  topics:
    inventory-events: inventory-events
    inventory-events-dlq: inventory-events-dlq

# SpringDoc OpenAPI Configuration - Common settings
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
