name: Test GitHub Secrets

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual trigger

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test GitHub Secrets
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "🔐 GitHub Secrets Test"
          echo "===================="
          echo ""
          
          # Test each secret
          secrets_ok=true
          
          echo "📧 Email Configuration:"
          if [ -n "$MAIL_USERNAME" ]; then
            echo "  ✅ MAIL_USERNAME: configured"
          else
            echo "  ❌ MAIL_USERNAME: missing"
            secrets_ok=false
          fi
          
          if [ -n "$MAIL_PASSWORD" ]; then
            echo "  ✅ MAIL_PASSWORD: configured"
          else
            echo "  ❌ MAIL_PASSWORD: missing"
            secrets_ok=false
          fi
          
          echo ""
          echo "🔑 Security Configuration:"
          if [ -n "$JWT_SECRET" ]; then
            echo "  ✅ JWT_SECRET: configured"
          else
            echo "  ❌ JWT_SECRET: missing"
            secrets_ok=false
          fi
          
          if [ -n "$INTERNAL_API_KEY" ]; then
            echo "  ✅ INTERNAL_API_KEY: configured"
          else
            echo "  ❌ INTERNAL_API_KEY: missing"
            secrets_ok=false
          fi
          
          echo ""
          echo "🗄️ Database & Cache:"
          if [ -n "$REDIS_PASSWORD" ]; then
            echo "  ✅ REDIS_PASSWORD: configured"
          else
            echo "  ❌ REDIS_PASSWORD: missing"
            secrets_ok=false
          fi
          
          if [ -n "$DB_PASSWORD" ]; then
            echo "  ✅ DB_PASSWORD: configured"
          else
            echo "  ❌ DB_PASSWORD: missing"
            secrets_ok=false
          fi
          
          echo ""
          echo "📋 Summary:"
          if [ "$secrets_ok" = true ]; then
            echo "🎉 All GitHub Secrets are properly configured!"
            echo "✅ Your microservices platform is ready for deployment"
          else
            echo "⚠️  Some secrets are missing or not configured"
            echo "📝 Please add the missing secrets:"
            echo "   1. Go to GitHub repository Settings"
            echo "   2. Navigate to Secrets and variables → Actions"
            echo "   3. Add the missing secrets listed above"
            echo "   4. See SETUP_GITHUB_SECRETS.md for detailed instructions"
            exit 1
          fi
